### ISSUE TITLE
zrob lepszy kod XDDDDDDDDDD

### ISSUE THREAD

**Issue by VexioPLL** [narumii/AlpheratzDeobfuscator#1]
ale tu jest duzo gowno kodu XDXDDDDDDDDDD

**Comment by Szumir** [comment]
ok.

**Comment by Szumir** [comment]
napisał to veixo..

**Comment by narumii** [comment]
te uczucie gdy piszesz ze cos ma gowno kod a nie potrafisz napisac w ktorym miejscu niczym unix chociaz nawet ciebie rozumiem bo jedyna klasa jaka rozumiesz to bootstrap

**Comment by narumii** [comment]
oraz nie jestem najlepsza osoba do prowokowania ;)
